[tool.poetry]
name = "fd-intraeeg"
version = "0.1.0"
description = ""
authors = ["Jihagen <j.i.hagen@t-online.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
